export default {
  defaultState: {
    circleDays: 33,
    circleInitiatedAt: '2017-04-28T00:00:00Z',
    currentTime: '2017-04-30T00:00:00Z',
    money: 120000,
    accountabilities: [{
      id: 1,
      label: 'My Place',
      type: 'substraction',
      perCircle: 130000
    }, {
      id: 2,
      label: 'Savings',
      type: 'percentage',
      perCircle: 10
    }, {
      id: 3,
      label: 'Seguro Vida',
      type: 'substraction',
      perCircle: 4800
    }, {
      id: 4,
      label: 'Nubank',
      type: 'substraction',
      perCircle: 5582
    }, {
      id: 6,
      label: 'Seguro Cartão',
      type: 'substraction',
      perCircle: 660
    }, {
      id: 7,
      label: 'Itau',
      type: 'substraction',
      perCircle: 2570
    }, {
      id: 8,
      label: 'Carro',
      type: 'substraction',
      perCircle: 150000
    }, {
      id: 9,
      label: 'Longboard',
      type: 'substraction',
      perCircle: 20000
    }],
    dailyExpenses: [{
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }, {
      id: 1,
      label: 'Breakfest',
      amount: 2000
    }]
  }
}
